
SELECT * FROM STUDENT NATURAL JOIN ENROL; --1

SELECT STUDENT.STU_NO,STU_NAME,SUB_NAME,ENR_GRADE FROM ENROL, STUDENT, SUBJECT; --2

SELECT SUB_NAME,STU_NO,ENR_GRADE FROM STUDENT NATURAL JOIN ENROL,SUBJECT; --3

SELECT SUB_NAME,STU_NO,ENR_GRADE FROM SUBJECT JOIN ENROL USING (SUB_NO); 
--4 ( '()' 안에 들어가는건 포함되지 않는것이어야함. 포함되는것이면 실행이 안됨.

SELECT STU_NAME FROM STUDENT,ENROL WHERE ENR_GRADE>=70; --5

SELECT STU_NAME FROM STUDENT JOIN ENROL USING (STU_NO) WHERE ENR_GRADE>=60; --6

SELECT DISTINCT STU_NAME FROM STUDENT NATURAL JOIN ENROL WHERE ENR_GRADE<=70; --7

SELECT ENROL.SUB_NO,SUB_NAME,SUB_PROF FROM ENROL,STUDENT,SUBJECT WHERE STUDENT.STU_NO=ENROL.STU_NO AND STU_NAME='김인중' AND SUBJECT.SUB_NO=ENROL.SUB_NO; --8

SELECT SUB_NAME,SUB_PROF FROM ENROL NATURAL JOIN SUBJECT NATURAL JOIN STUDENT WHERE STU_NAME='김인중'; --9

SELECT SUB_NAME,SUB_PROF FROM ENROL JOIN STUDENT USING (STU_NO) JOIN SUBJECT USING (SUB_NO) WHERE STU_NAME='김인중'; --10

SELECT STU_NAME FROM ENROL JOIN STUDENT USING(STU_NO) JOIN SUBJECT USING(SUB_NO) WHERE SUB_PROF='강종영'; --11

SELECT STU_NO,STU_NAME FROM ENROL NATURAL JOIN STUDENT NATURAL JOIN SUBJECT WHERE SUB_NAME='컴퓨터개론'; --12

SELECT STU_NO, STU_NAME FROM ENROL NATURAL JOIN STUDENT NATURAL JOIN SUBJECT WHERE SUB_NAME='시스템분석설께' UNION SELECT STU_NO, STU_NAME FROM ENROL NATURAL JOIN STUDENT NATURAL JOIN SUBJECT WHERE SUB_NAME='소프트웨어공학'; --13

SELECT STU_NO, STU_NAME FROM ENROL NATURAL JOIN STUDENT NATURAL JOIN SUBJECT WHERE SUB_GRADE=1 UNION SELECT STU_NO, STU_NAME FROM ENROL NATURAL JOIN STUDENT NATURAL JOIN SUBJECT WHERE STU_DEPT='컴퓨터정보';--14

SELECT STU_NO,STU_NAME FROM ENROL NATURAL JOIN STUDENT NATURAL JOIN SUBJECT WHERE SUB_NAME='기계공작법' UNION SELECT STU_NO,STU_NAME FROM ENROL NATURAL JOIN STUDENT NATURAL JOIN SUBJECT WHERE SUB_NAME='기초전자실험'; --15

SELECT STU_NO FROM ENROL JOIN STUDENT USING (STU_NO)JOIN SUBJECT USING (SUB_NO) WHERE SUB_PROF='김태영' UNION SELECT STU_NO FROM ENROL JOIN STUDENT USING (STU_NO)JOIN SUBJECT USING (SUB_NO) WHERE SUB_PROF='김유섭'; --16

SELECT STU_NAME,ENR_GRADE FROM SUBJECT NATURAL JOIN ENROL NATURAL JOIN STUDENT; --17

SELECT *
FROM SUBJECT;
SELECT SUB_NAME FROM SUBJECT NATURAL JOIN ENROL WHERE STU_NO=20153075; --18

SELECT SUB_NAME FROM SUBJECT NATURAL JOIN STUDENT WHERE STU_GENDER='F'; --19미완성

select distinct sub_name from subject natural join student where stu_weight<=60;